version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-24-ndk

    working_directory: ~

    environment:
      MIN_SDK_VERSION: 21
      HOST_TAG: linux-x86_64

    steps:
      - checkout

      - run: git submodule update --init --recursive

      - run: sudo sh -c "apt update && apt install autoconf libtool"

      - run: chmod +x ./build.sh && ./build.sh

      - run: tar cvzf curl.tar.gz build

      - store_artifacts:
          path: curl.tar.gz

  publish-github-release:

    docker:

      - image: cibuilds/github:0.10

    steps:

      - attach_workspace:

          at: ./artifacts

      - run:

          name: "Publish Release on GitHub"

          command: |

            VERSION=$(my-binary --version)

            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
