version: 2.1

orbs:
  android: circleci/android@2.1.2

jobs:
  setup:
    docker:
      - image: cimg/android:2023.08
    steps:
      - checkout
      - run:
          name: Update submodules
          command: git submodule update --init --recursive
      - run:
          name: Install dependencies
          command: |
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C0BA5CE6DC6315A3
            sudo apt update && sudo apt install -y autoconf libtool pkg-config
      - persist_to_workspace:
          root: .
          paths:
            - .

  build_openssl:
    docker:
      - image: cimg/android:2023.08
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build OpenSSL
          command: |
            chmod +x ./build-openssl.sh
            ./build-openssl.sh
      - persist_to_workspace:
          root: .
          paths:
            - build/openssl

  build_curl:
    docker:
      - image: cimg/android:2023.08
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build cURL
          command: |
            chmod +x ./build-curl.sh
            ./build-curl.sh
      - persist_to_workspace:
          root: .
          paths:
            - build/curl

  package:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Package artifacts
          command: |
            tar cvzf curl.tar.gz build
            echo "$(git -C curl describe --abbrev=0)_$(git -C openssl describe --abbrev=0)" > VERSION
      - store_artifacts:
          path: curl.tar.gz
      - persist_to_workspace:
          root: .
          paths:
            - curl.tar.gz
            - VERSION

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(cat ./VERSION)
            mv ./curl.tar.gz ./${VERSION}.tar.gz
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./${VERSION}.tar.gz

workflows:
  version: 2
  build-and-publish:
    jobs:
      - setup
      - build_openssl:
          requires:
            - setup
      - build_curl:
          requires:
            - build_openssl
      - package:
          requires:
            - build_curl
      - publish-github-release:
          requires:
            - package
          filters:
            branches:
              only: main
